# Use a imagem do Node.js LTS como base
FROM node:lts-alpine AS builder

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos de configuração
COPY package.json ./

# Instale as dependências
RUN npm install --frozen-lockfile

# Copie todos os arquivos do projeto
COPY . .

# Construa o projeto Vite com TypeScript
RUN npm run build

# Inicie uma nova fase
FROM nginx:alpine

# Copie os arquivos de construção do projeto Vite para o diretório de documentos padrão do nginx
COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponha a porta 80
EXPOSE 80

# Inicie o servidor nginx em primeiro plano
CMD ["nginx", "-g", "daemon off;"]